-- phpMyAdmin SQL Dump
-- version 4.9.7
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3306
-- Generation Time: Jul 29, 2021 at 10:32 AM
-- Server version: 10.3.28-MariaDB-log-cll-lve
-- PHP Version: 7.3.28

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `stjohqse_Wizarddb`
--

-- --------------------------------------------------------

--
-- Table structure for table `stud_de`
--

CREATE TABLE `stud_de` (
  `stud_id` int(11) NOT NULL,
  `stud_code` varchar(15) NOT NULL,
  `stud_cl` int(2) NOT NULL,
  `stud_subcl` int(2) NOT NULL,
  `stud_level` int(2) NOT NULL,
  `stud_term` int(2) NOT NULL,
  `anual_set` int(2) NOT NULL,
  `stud_status` int(2) NOT NULL,
  `stud_note` varchar(1500) NOT NULL,
  `rector_not` varchar(1500) NOT NULL,
  `stud_subj` varchar(100) NOT NULL,
  `date_set` varchar(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `stud_de`
--

INSERT INTO `stud_de` (`stud_code`, `stud_note`, `rector_not`) VALUES
('SJBSI2031525', '[\"Okoye John Bosco\",\"Daniel is diligent, but he has to pay attention to his Book keeping.\"]', '[\"Promoted\",\"Good result. But there is more room for improvement. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2048404', '[\"Okoye JohnBosco \",\"A very poor performance Paschal please begin to make efforts to at least justify your stay here. All hope is not lost yet!\"]', '[\"Promoted\",\"This is not a wonderful result. Paschal should make serious efforts especially in the failed subjects. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2088974', '[\"Okoye JohnBosco \",\"Victor did well and is encouraged to aim higher and get a more comfortable distinction especially in Mathematics.\"]', '[\"Promoted\",\"Mathematics is a snare lurking in the shadows. Be wary of the challenges posed, and sit up. Not a wonderful result\",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2030644', '[\"Okoye JohnBosco \",\"Val. you really need to take your assessments serious otherwise you may make your records a lot messier. However he is a quiet seminarian.\"]', '[\"Promoted\",\"Poor result. Mathematics is becoming a serious threat. Stand up to your feet and say no to your defeat! Conduct satisfactory\",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2048128', '[\"Okoye JohnBosco \",\"Am not surprised at his result because even though he appears a bit playful it does not encroach into his academics.\"]', '[\"Promoted\",\"Fair result. Keep making effort. Conduct satisfactory\",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2071817', '[\"Okoye JohnBosco \",\"A very big congratulations to Patrick really hard-work pays. Do not slacken!\"]', '[\"Promoted\",\"Wonderful result!!! Keep it up. Strive to be the best! \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2048872', '[\"Okoye JohnBosco \",\"A nice result but he should endeavor to keep off little failures from his efforts. A focused seminarian \"]', '[\"Promoted\",\"This is not a wonderful result. Pay attention to the threats posed by Mathematics and a number of other subjects. Conduct satisfactory\",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2013638', '[\"Okoye JohnBosco \",\"A very good result, keep it up Daniel.\"]', '[\"Promoted\",\"Fairly good result. Keep making effort! Good conduct\",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2031607', '[\"Okoye JohnBosco \",\"Congratulations JohnMark you took the bold step and it paid off! Keep it up.\"]', '[\"Promoted\",\"Very good result! Keep striving for better result. Do not relax! \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2096828', '[\"Okoye JohnBosco \",\"Charles, you have to make you success emphatic next time, beware of Mathematics and Book keeping. Kudos to you still \"]', '[\"Promoted\",\"Good result, but Mathematics was a narrow escape! Beware of the danger lurking in the shadows, and respond accordingly. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2036298', '[\"Okoye JohnBosco \",\"A comfortable success but you can actually aim higher.\"]', '[\"Promoted\",\"Good result. But you can do better still, the challenges of being the Senior Prefect notwithstanding. Exemplary conduct. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2081247', '[\"Okoye JohnBosco \",\"Congratulations Boniface you made it \"]', '[\"Promoted\",\"Wonderful result. Boniface has maintained a strong academic stability, and should be encouraged to keep the flag flying. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2083494', '[\"Okoye JohnBosco \",\"Appears to be a good result but you do not need to give failure any chances of finding you\"]', '[\"Promoted\",\"Fair result. But beware of the dangers posed by Computer Science and Mathematics, and respond accordingly. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2018988', '[\"Okoye JohnBosco \",\"A good result keep it up and aim higher still.\"]', '[\"Promoted\",\"Fairly good result. There is room for improvement. Conduct satisfactory\",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2063926', '[\"Okoye JohnBosco \",\"A good result keep it up and make the most out of your scores \"]', '[\"Promoted\",\"Good result. Keep striving for better result. Conduct satisfactory\",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2094897', '[\"Okoye JohnBosco \",\"A good result but beware of Book-Keeping and little failures\"]', '[\"Promoted\",\"Mathematics was a narrow escape, plus other low grades. Beware of the danger lurking in the shadows. Conduct satisfactory\",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2083827', '[\"Okoye JohnBosco \",\"A nice effort but you can still make the best out of your scores\"]', '[\"Promoted\",\"A poor result. He can do much better if he makes more effort. Conduct satisfactory\",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2037372', '[\"Okoye JohnBosco \",\"You scaled through but you can actually pass in a better and safer way. \"]', '[\"Promoted\",\"Poor result. Pls sit up or risk failure. Conduct satisfactory\",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2065993', '[\"Okoye JohnBosco \",\"A good result from a responsible seminarian but beware of Book -Keeping next time.\"]', '[\"Promoted\",\"Fair result, but more effort is needed especially in Mathematics and Book Keeping. Conduct satisfactory\",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2014224', '[\"Okoye JohnBosco \",\"Failing two Art subjects raises my concerns for your final examination. Please avoid any failure next time \"]', '[\"Promoted\",\"Fair result, but pay serious attention to the failed subjects next time. Conduct satisfactory\",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2065479', '[\"Okoye JohnBosco \",\"A good result but beware of Book-Keeping \"]', '[\"Promoted\",\"Fair result. Pay more attention to Book Keeping, Literature and Mathematics. Conduct satisfactory.\\r\\n\",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2068851', '[\"Okoye JohnBosco \",\"You passed this time but you have to change your attitude towards assessment tests \"]', '[\"Promoted\",\"Fair result. But the failures in science subject are serious concerns. Please take them more serious. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2017753', '[\"Okoye JohnBosco \",\"A good one but u can aim higher. Pay more attention to Physics too.\"]', '[\"Promoted\",\"There is a noticeable poor performance in the science subjects, especially Mathematics and Physics. Please sit up! Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2048189', '[\"Okoye JohnBosco \",\"Michael seems does not seem to be picking up and his academics is threatened by his attitude to academics. All hope is not lost yet!\"]', '[\"Promoted\",\"Very poor result. Michael is yet to prove that he is serious. He should be advised to face his studies squarely, as that has become a big challenge for him. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2074381', '[\"Okoye JohnBosco \",\"Congratulations Casmir but you would have become the best if you paid attention to Mathematics.\"]', '[\"Promoted\",\"A very good result. He can do better still. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2074847', '[\"Okoye JohnBosco \",\"A nice result you deserve a kudos!\"]', '[\"Promoted\",\"Good result. Keep it up! \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2089812', '[\"Okoye JohnBosco \",\"A good result keep it up. Do not relax yet!\"]', '[\"Promoted\",\"Good result. Pay more attention to Physics\",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2083098', '[\"Okoye JohnBosco \",\"A very good result do not relax yet!\"]', '[\"Promoted\",\"Nice result. Pay more attention to Mathematics and Book Keeping. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2079618', '[\"Okoye JohnBosco \",\"A very happy and recommendable result keep on soaring Mathew\"]', '[\"Promoted\",\"Nice result. Keep it up. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2077580', '[\"Okoye JohnBosco \",\"A very commendable show of diligence keep up the good work \"]', '[\"Promoted\",\"Pls pay serious attention to science subjects. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2071839', '[\"Okoye JohnBosco \",\"A good show of resilience keep up the good work and be more careful next time not to neglect any subject \"]', '[\"Promoted\",\"An otherwise good result, but for the glaring failure in Computer Science. Conduct satisfactory\",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2041174', '[\"Okoye JohnBosco \",\"A pity you seem not to be putting in The required efforts and skills in your academics but judging from your good manners you can make it if only you try harder.  \"]', '[\"Promoted\",\"Very poor result. Please pay serious attention to your studies. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2044652', '[\"Okoye JohnBosco \",\"A very poor result you really need to buckle up else you might end up repeating the class.\"]', '[\"Promoted\",\"Pls pay serious attention to science subjects and Book Keeping.  Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2012344', '[\"Okoye JohnBosco \",\"A good result keep it up. He is growing in responsibility by the day\"]', '[\"Promoted\",\"Fairly good result. Pay more attention to Chemistry. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2053546', '[\"Okoye JohnBosco \",\"I am particularly happy with this performance as it matches your performance in the other various aspects of your formation. Kudos!\"]', '[\"Promoted\",\"Very good result. More effort it needed for better result. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2048533', '[\"Okoye JohnBosco \",\"A fair result Please keep pushing you are not there yet\"]', '[\"Promoted\",\"Very poor result. Serious effort should be made to face the challenges posed by both the core and science subjects. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2033125', '[\"Mr. Athanasius Ikegbusi \",\"This is a good result, I am sure that you have a target, pursue it and you will get there. \"]', '[\"Promoted\",\"A very good result. But you can do better still. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2072547', '[\"Okoye JohnBosco \",\"You passed for the term but as a science student you have to really sit up.\"]', '[\"Promoted\",\"Poor result. The challenge posed by the science subjects is glaring. It calls for more serious studies on your part. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2011245', '[\"Okoye JohnBosco \",\"Your carelessness has cost you the second term be very careful and pick up in the coming term\"]', '[\"Promoted\",\"Not a wonderful result. And Mathematics in particular has become a threat. Do not allow it to win you again. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2036086', '[\"Okoye JohnBosco \",\"Three fails is not a good sign please buckle up, especially in your sciences\"]', '[\"Promoted\",\"Please pay serious attention to science subjects and Mathemtics. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2094865', '[\"Okoye JohnBosco \",\"Mathematics is not so difficult. There is need for serious improvements. \"]', '[\"Promoted\",\"Poor result. Please pay serious attention to Mathematics and Book Keeping. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2093798', '[\"Okoye JohnBosco \",\"Surprising how you managed to pass with your position. Thank God for that but you need to work harder to avoid mediocrity!\"]', '[\"Promoted\",\"Poor result. Please sit up and face your studies for a better result. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2033950', '[\"Okoye JohnBosco \",\"Mathematics is not difficult! Your efforts are recognized this term but you have more energy in you to push harder so why not push?\"]', '[\"Promoted\",\"You can do better than this, Emmanuel. Try to make your parents proud. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2047835', '[\"Okoye JohnBosco \",\"A very commendable effort but you still have to rise above mediocrity this time.\"]', '[\"Promoted\",\"Please pay serious attention to science subjects and Book Keeping. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2006809', '[\"Okoye JohnBosco \",\"Well done job! You need to aim higher and you will be among the very best!\"]', '[\"Promoted\",\"Fair result. Please pay serious attention to Mathematics and Book Keeping. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2044644', '[\"Mr. Athanasius Ikegbusi \",\"Clement, you went back. \\r\\nMake effort to get back to your stand. \\r\\nA good result anyways. \"]', '[\"Promoted\",\"There is a marked recession in your performance. Try to correct that next time. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2075895', '[\"Mr. Athanasius Ikegbusi\",\"He is a serious student, but should pay more attention to mathematics.\"]', '[\"Promoted\",\"Good result. JohnPaul can still do better than this.\",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2056850', '[\"Mr. Athanasius Ikegbusi\",\"John is studious, but loses concentration easily.\\r\\nStill, you can do more than this.\"]', '[\"Promoted\",\"Wonderful result! Do not rest on your oars, John. Make more efforts! \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2014908', '[\"Mr. Athanasius Ikegbusi\",\"Emmanuel appears serious always, but does not have full spirit for it.\\r\\nThis is a poor performance.\"]', '[\"Promoted\",\"A very poor result. And Mathematics is becoming a threat to your academic balance. Sit up! \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2050831', '[\"Mr. Athanasius Ikegbusi\",\"Chinonso, please make a wise choice of subjects you can offer.\\r\\nThis result is not satisfactory.\"]', '[\"Promoted\",\"Good result. But pay attention to Mathematics. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2086869', '[\"Mr. Athanasius Ikegbusi\",\"Charlse is intelligent from observation, but lacks focus.\\r\\nYour position is not outstanding, watch out for Book Keeping.\"]', '[\"Promoted\",\"Good result. But pay attention to the threat posed by Mathematics. Good conduct\",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2086013', '[\"Mr. Athanasius Ikegbusi\",\"Chimdindu, is this really your result?\\r\\nYour result is good, but get back to your stand.\"]', '[\"Promoted\",\"Very good result, but you can do better. Keep it up. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2035688', '[\"Mr. Athanasius Ikegbusi\",\"Lawrence, this result is not fair at all.\\r\\nExtra effort is needed for improvement!\"]', '[\"Promoted\",\"Abysmally poor result. Lawrence needs to sit up and face his studies squarely, if he is to succeed. Please advise him thoroughly\",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2065607', '[\"Mr. Athanasius Ikegbusi\",\"Bona, this is unlike you, you know that you can do better than this.\\r\\nStop being uninterested. \"]', '[\"Promoted\",\"Good result, but you can do much better. Keep striving! Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2027917', '[\"Mr. Athanasius Ikegbusi\",\"Somtoo, you have a burning zeal, but apply it very well in your studies.\\r\\nBeware of physics!\"]', '[\"Promoted\",\"Fair result. More effort is needed especially in the subjects with low grades. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2063069', '[\"Mr. Athanasius Ikegbusi\",\"Stanley, avoid unneccessary distractions during studies.\\r\\nMore effort is needed.\"]', '[\"Promoted\",\"Fair result. But pay serious attention to Mathematics and Literature in English. Conduct satisfactory\",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2018489', '[\"Mr. Athanasius Ikegbusi\",\"Gerald, I least expected this from you.\\r\\nYour result is telling bad of you, IMPROVE!\"]', '[\"Promoted\",\"Gerald needs to buckle up in his studies. He can do much better than this. Conduct satisfactory\",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2048214', '[\"Mr. Athanasius Ikegbusi\",\"Benedict, what is red ink doing in your result?\\r\\nYou lack concentration a lot.\"]', '[\"Promoted\",\"Fair result, with serious need for improvement in Mathematics\",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2059273', '[\"Mr. Athanasius Ikegbusi\",\"Emma, you are gradually going back.\\r\\nYou can have a wonderful performance, it is in your hands if you wish. \"]', '[\"Promoted\",\"Fair result. Pay attention to the challenging subjects. Conduct satisfactory\",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2021643', '[\"Mr. Athanasius Ikegbusi\",\"Emma, I can see that you are improving.\\r\\ngood result, do not make this your end point, but your starting point.\"]', '[\"Promoted\",\"Good result! Keep it up! \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2087819', '[\"Mr. Athanasius Ikegbusi\",\"Please John, I do not think that sciences is the best option for you, try art courses.\\r\\nYou need another resolution.\"]', '[\"Promoted\",\"A very poor result! Please sit up or risk failure\",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2038783', '[\"Mr. Athanasius Ikegbusi\",\"David what is the problem?\\r\\nThis result is not fair at all, pay attention to yourself and mathematics.\"]', '[\"Promoted\",\"Generally, a poor result. Mathematics in particular has become a snare for you. Please give it more time. Conduct satisfactory\",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2088863', '[\"Mr. Athanasius Ikegbusi\",\"Chimdera, I expected something better than this.\\r\\nWake up already.\"]', '[\"Promoted\",\"Good result. But the science subjects are posing serious challenges to you. Stand up on your feet and say no to your defeat. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2029764', '[\"Mr. Athanasius Ikegbusi\",\"What were you thinking please?\\r\\nYou can still do well, improve.\"]', '[\"Promoted\",\"A very poor result! Failing almost five subject in this critical time of the session does not speak good of you. You had better sit up! \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2004168', '[\"Mr. Athanasius Ikegbusi\",\"Anthony, there is still room for improvement.\\r\\nBefriend the intelligent ones please!\\r\\nPay attention to physics and accounting.\"]', '[\"Promoted\",\"Very poor result. Please improve before it is too late. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2090443', '[\"Mr. Athanasius Ikegbusi\",\"What happened to your mathematics and book keeping?\\r\\nThere is still room for improvement.\"]', '[\"Promoted\",\"Poor result. Christian should be advised to face Mathematics squarely, as that has become a big challenge for him. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2062616', '[\"Mr. Athanasius Ikegbusi \",\"A good result, keep on improving. \"]', '[\"Promoted\",\"A good result. Keep making effort! Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2082249', '[\"Mr. Athanasius Ikegbusi \",\"Focus on your books first please. \\r\\nYou can still improve. \"]', '[\"Promoted\",\"Good result. But pay attention to Mathematics and Book Keeping. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2089037', '[\"Mr. Athanasius Ikegbusi\",\"What happened to physics please?\\r\\nImprove on this result, and give consideration to your physics.\"]', '[\"Promoted\",\"Poor result. Not just Physics, but several other subjects are seeking for your serious attention. Mathematics was a narrow escape. Please sit up. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2084189', '[\"Mr. Athanasius Ikegbusi \",\"Emmanuel, you are lacking focus in your studies, do something about it. \\r\\n\"]', '[\"Promoted\",\"There is serious need for improvement in science subjects and literature. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2028380', '[\"Mr. Athanasius Ikegbusi \",\"Your physics needs serious attention. \\r\\nStill you can improve on this result.  \"]', '[\"Promoted\",\"Pls pay serious attention to science subjects and Literature in English. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2082141', '[\"Mr. Athanasius Ikegbusi \",\"Your result is impressive, but you can still do more than this. \"]', '[\"Promoted\",\"A good result. Keep it up! Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2063974', '[\"Mr. Athanasius Ikegbusi \",\"This result is very bad, there is hope for improvement  only if you stop sleeping, and become serious. \"]', '[\"Promoted\",\"Poor result. Pls pay serious attention to Mathematics and Book Keeping. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2078414', '[\"Mr. Athanasius Ikegbusi \",\"You are not qualified for sciences at all. \\r\\nYou need to look into yourself properly. \\r\\nYou have a bad result, I hope you improve by 3rd term. \"]', '[\"Promoted\",\"Very poor result. Please pay serious attention to science subjects and Book Keeping. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2016031', '[\"Mr. Athanasius Ikegbusi \",\"Study hard and harder for better improvement. \\r\\nMathematics needs your full attention. \"]', '[\"Promoted\",\"Poor result. Mathematics and Book Keeping have become stumbling blocks that you must make serious effort to overcome. Satisfactory conduct. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2037782', '[\"Mr. Athanasius Ikegbusi \",\"What happened to your mathematics? \\r\\nYou need to sit up, so as not to fail again. \"]', '[\"Promoted\",\"Poor result. Why would you give Mathematics the chance to spoil your result?\\r\\nPlease sit up, and pay attention to Book Keeping too. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2049447', '[\"Okoye JohnBosco \",\"A very poor result you really need to buckle up else you might end up repeating the class.\"]', '[\"Promoted\",\"A very poor result. Dennis can do better than this if he becomes a bit more serious with his studies. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2044347', '[\"Mr. Athanasius Ikegbusi \",\"A science student should be able to pass physics. \\r\\nWork more for an excellent result. \"]', '[\"Promoted\",\"Fairly good result. But pay more attention to the failed subjects. Conduct satisfactory\",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2061685', '[\"Mr. Athanasius Ikegbusi \",\"This is a good result. \\r\\nMichael always exhibit interest in learning. \\r\\nKeep it up. \"]', '[\"Promoted\",\"A good result. Keep it up. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2063869', '[\"Mr. Athanasius Ikegbusi \",\"Nwokoye Charles Cijioke\"]', '[\"Promoted\",\"Good performance. There is room for improvement. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2066436', '[\"Mr. Athanasius Ikegbusi \",\"A good result. \\r\\nKeep it up, and keep pushing. \"]', '[\"Promoted\",\"Fair result. Keep making effort for better result. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2082442', '[\"Mr. Athanasius Ikegbusi \",\"Make attempt to improve on this result \\r\\nIt is just a fair trial. \"]', '[\"Promoted\",\"This is not a wonderful result, and you can surely do better than this. Please sit up and face your studies keenly. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2024645', '[\"Mr. Athanasius Ikegbusi \",\"A fair result. \\r\\nEmmanuel, I expect something better than this by 3rd term. \\r\\nYou can do more. \"]', '[\"Promoted\",\"Fairly good result. But pay more attention to the subjects that you nearly failed: Mathematics and the science subjects. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2096901', '[\"Mr. Athanasius Ikegbusi \",\"A pass result indeed, what about the average? \\r\\nBuckle up please! \"]', '[\"Promoted\",\"Poor result. Please pay serious attention to science subjects and Book Keeping. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2054509', '[\"Mr. Athanasius Ikegbusi \",\"You have the zeal for studies, put in more effort to get to your target. \\r\\nA good result anyways. \"]', '[\"Promoted\",\"Fairly good result. But Mathematics was a narrow escape. Please bend down and face it and Book Keeping. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2032534', '[\"Mr. Athanasius Ikegbusi \",\"I can\'t see any improvement. \\r\\nPlease regain your focus and study harder. \\r\\nGood result anyways. \"]', '[\"Promoted\",\"Innocent, there is a marked recession in your performance this term. Do not allow this to happen again. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2082811', '[\"Mr. Athanasius Ikegbusi \",\"Fair result, avoid distractions and reckless sleep. \\r\\nPut in more effort. \"]', '[\"Promoted\",\"Please pay serious attention to science subjects and Book Keeping. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2048246', '[\"Mr. Athanasius Ikegbusi \",\"Christian, take your studies serious please. \\r\\nReview your choice of courses. \"]', '[\"Promoted\",\"Poor result. Please pay serious attention to Mathematics, the science subjects and Book Keeping. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2031714', '[\"Mr. Athanasius Ikegbusi\",\"Joseph, your improvement can only locate you when you stop sleeping.\\r\\nYour result is not fair.\"]', '[\"Promoted\",\"Poor result. Please pay serious attention to Mathematics, the science subjects and Book Keeping. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2028297', '[\"Okoye JohnBosco \",\"Kingsley put in more efforts than he did the last time but it was unfortunate he couldn\\u2019t cross over. All hope is not lost yet \"]', '[\"Promoted\",\"A very poor result! Please make more effort! Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2143274', '[\"Mr. Raphael Aniofor\",\"Poor result... Paschal you have to sit up!\"]', '[\"Promoted\",\"Abysmally poor result. At this rate, you are gunning towards a repetition of the class. Please sit up and face your studies more seriously\",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2191205', '[\"Mr. Raphael Aniofor\",\"Nice result... Keep it up!\"]', '[\"Promoted\",\"Very good result. You can do better still. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2188579', '[\"Mr. Raphael Aniofor\",\"Excellent result... Keep it up!\"]', '[\"Promoted\",\"Excellent Result. Keep the flag flying! \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2187718', '[\"Mr. Aniofor Raphael\",\"A wonderful result Peter. Keep it up.\"]', '[\"Promoted\",\" This is not the best you can offer. Please make more effort. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2150377', '[\"Mr. Raphael Aniofor\",\"Marius is not serious especially with his function and academic life in the seminary. He needs to sit up!\"]', '[\"Promoted\",\"A good result than can be proved on! Keep striving. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2138988', '[\"Mr. Raphael Aniofor\",\"Henry can do more than this, he needs to put more effort.\"]', '[\"Promoted\",\"Latin and Government were narrow escapes; Two others were total failures. Please sit up and face the challenge! Conduct satisfactory\",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2186446', '[\"Mr. Raphael Aniofor\",\"Kevin is relaxing... He needs to sit up.\"]', '[\"Promoted\",\"A fairly good result. Keep making efforts for better grades. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2157657', '[\"Mr. Raphael Aniofor\",\"Peter you can do more than this.... You need to Sit up!\"]', '[\"Promoted\",\"Mathematics and Latin are snares lurking in the shadow.. stand up on your feet and say no to your defeat! \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2153780', '[\"Mr. Raphael Aniofor\",\"He needs to improve in his studies.\"]', '[\"Promoted\",\"Good result, but Economics was a narrow escape. Keep making efforts for better grades. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2129184', '[\"Mr. Raphael Aniofor\",\"Paschal you need to improve... You can do more than this.\"]', '[\"Promoted\",\"A fairly good result. But attention should be given to the core subjects. He should also be advised to control his temper. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2136432', '[\"Mr. Raphael Aniofor\",\"Emmanuel is a serious minded student who comports himself during studies. Nice result!\"]', '[\"Promoted\",\"A very good result. Keep making efforts for better grades. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2142181', '[\"Mr. Raphael Aniofor\",\"Damian is improving, I believe he can do more than this.\"]', '[\"Promoted\",\"Failing four subjects is not a good sign. Please sit up and face your studies more seriously. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2123665', '[\"Mr. Raphael Aniofor\",\"John Paul is not serious especially with his studies.... He needs to improve. Poor result!\"]', '[\"Promoted\",\"Failing too many subjects is not very encouraging. Please stand up on your feet and say no to your defeat. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2126198', '[\"Mr. Raphael Aniofor\",\"Collins is not serious with his academic life in the seminary... He needs to sit up!\"]', '[\"Promoted\",\"Poor result. Please give serious attention to Latin and Mathematics. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2173381', '[\"Mr. Raphael Aniofor\",\"\"]', '[\"Promoted\",\"A wonderful result. Keep making efforts for better grades. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2130148', '[\"Mr. Raphael Aniofor\",\"Charles you need to improve in your studies. Your performance is poor!\"]', '[\"Promoted\",\"Poor result. Mathematics and Economics are proving to be your Achilles\'s heels. Stand up on your feet and say no to your defeat. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2139849', '[\"Mr. Raphael Aniofor\",\"Emmanuel is easily distracted during studies, he needs to sit up.\"]', '[\"Promoted\",\"A fairly good result. Keep making efforts for better grades. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2148518', '[\"Mr. Raphael Aniofor\",\"Michael, your result is wonderful. Keep it up!\"]', '[\"Promoted\",\"A very good result. Keep making efforts for better grades, especially in Mathematics. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2191798', '[\"Mr. Raphael Aniofor\",\"Jude your performance is poor... You need to improve!\"]', '[\"Promoted\",\"A very poor result. Failure in as much as four subjects, including the core ones, is not a good sign. Please sit up. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2146612', '[\"Mr. Raphael Aniofor\",\"Mark you can do more than this...put more effort!\"]', '[\"Promoted\",\"Government and Economics are two of your weak point. Please give them attention for better result. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2179644', '[\"Mr. Raphael Aniofor\",\"Nice result... Keep it up!\"]', '[\"Promoted\",\"A very good result. Keep making efforts for better grades. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2131897', '[\"Mr. Raphael Aniofor\",\"Serious improvement is needed, Emmanuel you have to sit up.\"]', '[\"Promoted\",\"A very poor result. You can do better than this, Emmanuel. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2183864', '[\"Mr. Raphael Aniofor\",\"Vincent you can do more than this. Your performance is not wonderful!\"]', '[\"Promoted\",\"A fairly good result. Keep making efforts for better grades. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2151188', '[\"Mr. Raphael Aniofor\",\"Justin is making serious effort; I believe he can do more than this.\"]', '[\"Promoted\",\"Fair result. You can do better still. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2184988', '[\"Mr. Raphael Aniofor\",\"Valentine can better than this... He needs sit up.\"]', '[\"Promoted\",\"A fairly good result. Keep making efforts for better grades. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2141655', '[\"Mr. Raphael Aniofor\",\"Patrick this is not your best; you need to sit up.\"]', '[\"Promoted\",\"A fairly good result. Keep making efforts for better grades. He is a good seminarian. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2108857', '[\"Mr. Raphael Aniofor\",\"Emmanuel you can do more than this; this is not your best.\"]', '[\"Promoted\",\"A fairly good result. You can do better still. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2134751', '[\"Mr. Raphael Aniofor\",\"Paschal you need to sit up; you can do better than this.\"]', '[\"Promoted\",\"A fairly good result. Keep making efforts for better grades especially in Latin. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2188331', '[\"Mr. Raphael Aniofor\",\"He sleeps a lot during studies; he needs to sit up.\"]', '[\"Promoted\",\"A poor result, with many low grades. Please advise him to be more serious, and be more honest. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2159486', '[\"Mr. Raphael Aniofor\",\"Michael is easily distracted during studies; he needs to sit up.\"]', '[\"Promoted\",\"Poor result. Work toward a better result next time. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2179864', '[\"Mr. Raphael Aniofor\",\"Paschal you need to sit up; you are relaxing!\"]', '[\"Promoted\",\"A fairly good result. Keep making efforts for better grades. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2157598', '[\"Mr. Raphael Aniofor\",\"Shadrach is a promising student; I believe he can do better than this.\"]', '[\"Promoted\",\"A  good result. Keep making efforts for better grades. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2131126', '[\"Mr. Raphael Aniofor\",\"Marcellinus  is making serious effort; I believe he can do better than this.\"]', '[\"Promoted\",\"Poor result. Make effort to overcome the challenges posed by the subjects you failed. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2118378', '[\"Kenneth is easily distracted during studies; he needs to sit up!\",\"\"]', '[\"Promoted\",\"Poor result. Make more efforts\",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2158328', '[\"Evans is a hardworking seminarian; I believe he can do better than this.\",\"\"]', '[\"Promoted\",\"A fairly good result. Keep making efforts for better grades. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2127248', '[\"Mr. Raphael Aniofor\",\"Christian can do better than this; he needs to sit up.\"]', '[\"Promoted\",\"Not a wonderful result. Keep making efforts for better grades. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2114843', '[\"Mr. Raphael Aniofor\",\"Felix is a promising student; I believe he can do better than this.\"]', '[\"Promoted\",\"A fairly good result. Keep making efforts for better grades. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2172453', '[\"Onwuegbunam Jude.T \",\"Valentine you have to pay serious attention to your studies next term.\"]', '[\"Promoted\",\"He can do much better than this if he studies harder. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2194225', '[\"Onwuegbunam Jude T .\",\"Justin has a recalcitrant attitudes studies. He is advised to take his studies seriously next term\"]', '[\"Promoted\",\"Very poor result. Please advise him to sit up! \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2126365', '[\"Onwuegbunam Jude T .\",\"Nice result ........ Keep it up.\"]', '[\"Promoted\",\"A fairly good result. Keep making efforts for better result in character and learning. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2176854', '[\"Onwuegbunam Jude T .\",\"Donald is influenced by his friends, advise him to take his studies very serious next term.\"]', '[\"Promoted\",\"Poor result. He can do better than this. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2148839', '[\"Onwuegbunam Jude.T \",\"You have a lot of work to do on your studies Franklin. You have to improve on this.\"]', '[\"Promoted\",\"This is only a narrow escape. He should be advised to pay more attention to his studies. Satisfactory conduct. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2190642', '[\"Onwuegbunam Jude.T \",\"You need to improve on this result, also try as much as possible to avoid unnecessary distractions.\"]', '[\"Promoted\",\"A fairly good result. Keep making efforts for better grades. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2188215', '[\"Onwuegbunam Jude T .\",\"Lawrence always jokes around during studies. Advise him to pay close attention to his studies.\"]', '[\"Promoted\",\"Very poor result! Please advise him to sit up. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2134046', '[\"Onwuegbunam Jude T .\",\"Stephen tends to be unserious with his studies, caution him to study tirelessly.\"]', '[\"Promoted\",\"Very poor result. It is not surprising, considering his unseriousness and troublesome attitude during classes. Please advise him to make hay whike the sun shines. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2158822', '[\"Onwuegbunam Jude.T \",\"Emmanuel is an industrious seminary. Nice result, keep it up.\"]', '[\"Promoted\",\"A very good result. Keep making efforts for better grades. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2124686', '[\"Onwuegbunam Jude T .\",\"Vincent Paschal is very distracted during studies, advise him to avoid unnecessary distractions.\"]', '[\"Promoted\",\"A fairly good result. Keep making efforts for better grades and avoid troubles. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2106795', '[\"Onwuegbunam Jude T .\",\"Kelvin you have the potentials ......... explore it. Very poor result.\"]', '[\"Promoted\",\"Kelvin needs serious pieces of advice. He needs to sit up and make good use of his study time. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2157716', '[\"Onwuegbunam Jude T.\",\"Lotanna is very serious with his studies. Keep it up.\"]', '[\"Promoted\",\"A fairly good result. Keep making efforts for better grades. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2184382', '[\"Onwuegbunam Jude T.\",\"Victor is very dutiful. Nice result, keep it up. \"]', '[\"Promoted\",\"A very good result. Keep making efforts for better grades. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2154865', '[\"Onwuegbunam Jude T.\",\"Caution him to stop sleeping during studies, and to avoid unnecessary distraction.\"]', '[\"Promoted\",\"A very poor result. Please advise him to sit up! \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2198876', '[\"Onwuegbunam Jude T.\",\"Wonderful result....... Samuel is a serious minded seminarian.\"]', '[\"Promoted\",\"A very nice result. He is always improving. Encourage him all the more. Conduct quite satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2133955', '[\"Onwuegbunam Jude T .\",\"Fair result......... But you still have some work to do academically.\"]', '[\"Promoted\",\"This is not a wonderful result. Please advise him to sit up. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2127270', '[\"Onwuegbunam Jude T.\",\"Samuel is easily distracted.............. you have sit up.\"]', '[\"Promoted\",\"A very poor result. Please advise him to wake up from his slumber. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2158268', '[\"Onwuegbunam Jude T .\",\"Fair result..... Strive to study harder next term.\"]', '[\"Promoted\",\"He can do much better if he faces his studies squarely. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2115475', '[\"Onwuegbunam Jude T.\",\" Excellent result.............. Paschal is a diligent seminarian. Keep it up. \"]', '[\"Promoted\",\"A wonderful performance. Keep the giant strides alive! L\",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2116504', '[\"Onwuegbunam Jude T.\",\"He is very unserious with regard to his studies.\\r\\nEncourage him to do better.\"]', '[\"Promoted\",\"Emmanuel is yet to understand the importance of seriousness in studies and general self organization. Please advise him to sit up. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2189566', '[\"Onwuegbunam Jude T .\",\"Fair result...... Stanley you have to sit up.\"]', '[\"Promoted\",\"This is not an encouraging performance Stanley. Sit up and prove your mettle while you still can\",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2135182', '[\"Onwuegbunam Jude T .\",\"Nice result ........... But this is not your best. You have to sit up.\"]', '[\"Promoted\",\"Nice result. But there is room for improvement. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2157734', '[\"Onwuegbunam Jude T .\",\"Nice result........ But I expected something higher than this. You have to sit up.\"]', '[\"Promoted\",\" Good result that still needs improvement. Keep making efforts for better grades. Conduct satisfactory, but needs to watch his overconfidence. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2125284', '[\"Onwuegbunam Jude T .\",\"Fair result....... JohnPaul, you can achieve something higher than this. Sit up.\"]', '[\"Promoted\",\"Fair result. Keep making efforts for better grades. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2193551', '[\"Onwuegbunam Jude T.\",\"Nice result............ you have to sit up.\\r\\nHe is an industrious seminarian.\"]', '[\"Promoted\",\"A very good result that still needs improvement. Keep making efforts for better grades. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2109163', '[\"Onwuegbunam Jude T .\",\"Victory is intelligent but he finds it difficult to make good use of his time in studying. Nice result ....\"]', '[\"Promoted\",\"This result does not match his intellectual acumen. He can do better if he uses his time judiciously. Fair result. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2168333', '[\"Onwuegbunam Jude T.\",\"Excellent result ............ Keep it up\\r\\nHe is a good seminarian. \"]', '[\"Promoted\",\"A very good result! Impressive. Keep improving on this. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2183549', '[\"Onwuegbunam Jude T.\",\"Nice result ............ Keep it up.\\r\\nHe is very quiet.\"]', '[\"Promoted\",\"A very good result that still needs improvement. Keep making efforts for better grades. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2146888', '[\"Onwuegbunam Jude T .\",\"  Poor result...... Kingsley plays always and that affects his academic performance. Caution him to study seriously next term.\"]', '[\"Promoted\",\"Very poor result. Please caution him to be more studious and responsible. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2111242', '[\"Onwuegbunam Jude T.\",\"Excellent result.......... keep it up \\r\\nHe is always cheerful and dutiful.\"]', '[\"Promoted\",\"A wonderful performance!  Francis is docile and duty-conscious. He should be encouraged to keep that up. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2183078', '[\"Onwuegbunam Jude T .\",\"Paul is very lazy to study, he is also dirty in school......... You have to sit up.\"]', '[\"Promoted\",\"A very poor performance. Apart from studies, Paul should be encouraged to imbibe personal hygiene, as his classmates usually complain of him. He is a good child, nevertheless. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2104392', '[\"Onwuegbunam Jude T .\",\"Fair result...... Lawrence this is not the best of what you can offer. Sit up and study.\"]', '[\"Promoted\",\"A fairly good result that still needs improvement. Keep making efforts for better grades. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2149925', '[\"Onwuegbunam Jude T .\",\"Nice result ...... Keep it up.\\r\\nHe is dedicated to duties .\"]', '[\"Promoted\",\"A good result that still needs improvement. Keep making efforts for better grades. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2174941', '[\"Onwuegbunam Jude T .\",\"Poor result...... Gabriel is very incorrigible. Advise him to change his attitude and study tirelessly.\"]', '[\"Promoted\",\"Poor result. He needs to improve in character and learning. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2163243', '[\"Onwuegbunam Jude T .\",\"Poor result......... Victor you have to sit up. He attracts unnecessary distractions to himself during studies.\"]', '[\"Promoted\",\"Poor results. He needs to improve urgently. Conduct satisfactory\\r\\n\",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2136746', '[\"Onwuegbunam Jude T .\",\"Herbert this is not your best. You have to improve on this result.\"]', '[\"Promoted\",\"This is a poor result. Put in more effort. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2179641', '[\"Onwuegbunam Jude T .\",\"Valentine is always distracted during studies. Adivse him to avoid unnecessary distractions.\"]', '[\"Promoted\",\"This is not a wonderful performance. Improve on this! Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2161366', '[\"Onwuegbunam Jude T .\",\"Nice result........ Keep it up\\r\\nHe is serious with his studies.\"]', '[\"Promoted\",\"A very good result that still needs improvement. Keep making efforts for better grades. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2146815', '[\"Onwuegbunam Jude T .\",\"Excellent result..... Keep it up.\\r\\nHe is very industrious.\"]', '[\"Promoted\",\"A very good result that still needs improvement. Keep making efforts for better grades eepecially in Igbo amd French. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2138918', '[\"Onwuegbunam Jude T .\",\"Poor result....... Kelvin you need to stop deceiving yourself and study genuinely.\"]', '[\"Promoted\",\"Poor result. Please advise him to be serious with his academic life. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2194438', '[\"Onwuegbunam Jude T .\",\"Fair result........ But you have to stop sleeping during studies and study seriously next term.\"]', '[\"Promoted\",\"Fair result that still needs improvement. Keep making efforts for better grades. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2176883', '[\"Onwuegbunam Jude T .\",\"Excellent result......... Keep it up\\r\\nHe is diligently dedicated to his studies and duties.\"]', '[\"Promoted\",\"Excellent result! Sixtus is dedicated to his studies. He needs however to work more on his speech challenges, and develop his communication skills. Conduct quite satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2145227', '[\"Onwuegbunam Jude T .\",\"Excellent result ...... Keep it up\\r\\nHe is passionate with regard to his studies.\"]', '[\"Promoted\",\"A very good result that still needs improvement. Keep making efforts for better grades. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2105459', '[\"Onwuegbunam Jude T .\",\"Nice result....... Improve on this result. He is always cheerful.\\r\\n\\r\\n\"]', '[\"Promoted\",\"Nice result. There is room for improvement. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2137648', '[\"Onwuegbunam Jude T .\",\"You made a great improvement this term Thomas. But you have to stop sleeping during studies in order to improve on this. \"]', '[\"Promoted\",\"An improved result that still needs further improvement. Keep making efforts for better grades. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2141716', '[\"Onwuegbunam Jude T .\",\"Amazing result......... Keep it up\\r\\nHe is dedicated to his studies.\"]', '[\"Promoted\",\"A very good result that still needs improvement. Keep making efforts for better grades. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2199867', '[\"Onwuegbunam Jude T .\",\"Fair result ....... Peter you have to sit up.  He is dutiful.\"]', '[\"Promoted\",\"A fair result that still needs improvement. Keep making efforts for better grades. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2119368', '[\"Onwuegbunam Jude T .\",\"Nice result ....... Keep it up\\r\\nJude distracted himself last term, please advise him to face his studies squarely next term.\"]', '[\"Promoted\",\"Fairly good result. But Jude is cut out for better result than this! He seems always homesick, and this landed him into mischiefs. Please advise him. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2174536', '[\"ENECHUKWU EMMANUEL\",\"Nice result. Christabel needs to put more effort in his studies.\"]', '[\"Promoted\",\"This is not your best, Christabel! Pay serious attention to the failed subjects next time. Satisfactory conduct. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2187454', '[\"ENECHUKWU EMMANUEL\",\"Satisfactory. Samuel can do more than this if he puts more effort in his studies and avoid distraction.\"]', '[\"Promoted\",\"A fairly good result. Keep making efforts for better grades. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2152295', '[\"Mr. Emmanuel Enechukwu\",\"Nice result. Keep it up.\"]', '[\"Promoted\",\"Nice result. Keep making efforts for better grades. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2158637', '[\"Mr. Emmanuel Enechukwu\",\"Excellent result. Paschal is a studious seminarian and he can do more than this. \"]', '[\"Promoted\",\"A good result. Keep making efforts for better grades. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]');
INSERT INTO `stud_de` (`stud_code`, `stud_note`, `rector_not`) VALUES
('SJBSI2128397', '[\"Mr. Emmanuel Enechukwu\",\"This is a poor result, Emmanuel needs to pay attention to his studies.\\r\\nThere is hope for improvement.\"]', '[\"Promoted\",\"Poor result. He plays a lit, and needs more seriousness in general school conduct\",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2192778', '[\"Mr. Emmanuel Enechukwu\",\"This is not a fair result at all.\\r\\nStick to your books always.\"]', '[\"Promoted\",\"A very poor result. He should be advised to study harder. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2114682', '[\"Mr. Emmanuel Enechukwu\",\"This is a wonderful result, keep it up.\\r\\nStick to your target.\"]', '[\"Promoted\",\"A very good result. Do not rest on your oars! Keep making efforts for better grades. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2141958', '[\"Mr. Emmanuel Enechukwu\",\"A nice result, please keep it up and make it your starting point.\"]', '[\"Promoted\",\"A very good result that can be improved upon. Keep making efforts for better grades. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2135476', '[\"Mr. Emmanuel Enechukwu\",\"Poor result. Henry needs to pay serious attention to his studies.\\r\\n\"]', '[\"Promoted\",\"Poor result. Please advise him to bend down and study. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2153410', '[\"Mr. Emmanuel Enechukwu\",\"This result is even away from fairness, improvement is needed seriously.\"]', '[\"Promoted\",\"Very poor result. Please advise him to be serious in class and avoid distractions. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2123331', '[\"Mr. Emmanuel Enechukwu\",\"Very poor result. Kizito is easily distracted during studies.He should put more effort in his studies.\"]', '[\"Promoted\",\"A very poor result. Kizito needs to be more serious with his seminary training in general, and studies in particular. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2190077', '[\"Mr.Emmanuel Enechukwu\",\"A good result. \\r\\nYou already have a target, pursue it and never give up.\"]', '[\"Promoted\",\"There is marked improvement in Augustine\'s life since after the last incident. He is doing well and should be encouraged all the more. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2146123', '[\"Mr.Emmanuel Enechukwu\",\"Nice improvement. keep it up.\"]', '[\"Promoted\",\"A fairly good result. Keep making efforts for better grades. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2116212', '[\"Mr.Emmanuel Enechukwu\",\"Raphael, this is a wonderful result indeed .\\r\\nYou have done well again.\\r\\nKeep it up. \"]', '[\"Promoted\",\"An excellent result. Raphael is calm, focused, docile and intelligent. Encourage him all the more to maintain this academic stability! \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2159571', '[\"Mr.Emmanuel Enechukwu\",\"Victor is a studious seminarian, but he sleeps a lot during studies.\\r\\nMore attention is needed in studies to perform better than this.\"]', '[\"Promoted\",\"A fairly good result. But you can do much better than this. Keep making efforts for better grades. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2174637', '[\"Mr. Emmanuel Enechukwu\",\"Michael is too playful but smart, if he should convert his play time to his study time,he will do great.\"]', '[\"Promoted\",\"He can do better than this. Please advise him to be  more serious. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2189986', '[\"Mr. Enechukwu Emmanuel \",\"Nice result. Emmanuel can do more than this if he decides to put in his best\"]', '[\"Promoted\",\"A fairly good result. Keep making efforts for better grades especially in Basic Technology. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2102728', '[\"Mr. Emmanuel Enechukwu\",\"Nice result. Francis can do more than this. \"]', '[\"Promoted\",\"\\r\\nA good result. He can actually do better. Conduct satisfactory.\",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2184665', '[\"Mr. Enechukwu Emmanuel \",\"Fair result. Emmanuel needs to put more effort in his studies\"]', '[\"Promoted\",\"A fairly good result. Keep making efforts for better grades. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2157603', '[\"Mr. Enechukwu Emmanuel \",\"Augustine should pay serious attention to his studies. \"]', '[\"Promoted\",\"A fairly good result. Keep making efforts for better grades. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2116426', '[\"Mr. Enechukwu Emmanuel \",\"Nice result. Keep improving. \"]', '[\"Promoted\",\"A fairly good result. Keep making efforts for better grades. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2191114', '[\"Mr. Enechukwu Emmanuel \",\"Wonderful result. Paul is a serious minded seminarian and he does not joke with his studies. \"]', '[\"Promoted\",\"Nice result! Keep making efforts for better grades. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2146677', '[\"Mr. Enechukwu Emmanuel \",\"Nice result. Justin can improve on this result if he decides to stop sleeping during studies. \"]', '[\"Promoted\",\"A nice result. Justin can do even better. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2162369', '[\"Mr. Enechukwu Emmanuel \",\"Nice result. Keep improving. \"]', '[\"Promoted\",\"Joseph can do better if he studies more and plays less. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2133897', '[\"Mr. Enechukwu Emmanuel \",\"Very poor result. Kingsley is easily distracted during studies. He should pay serious attention to his studies so that he can succeed in the following term. \"]', '[\"Promoted\",\"A very poor result. Please advise him to study harder. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2197965', '[\"Mr. Enechukwu Emmanuel \",\"Nice result. Divine needs to put in his best in his studies and also avoid distraction. \"]', '[\"Promoted\",\"A fair result. Improve on this. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2173885', '[\"Mr. Enechukwu Emmanuel \",\"Wonderful result. Keep improving. \"]', '[\"Promoted\",\"A very good result that still needs improvement. Keep making efforts for better grades. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2197128', '[\"Mr. Enechukwu Emmanuel \",\"Nice result. Emmanuel is a studious seminarian and he can do more than this. Keep improving. \"]', '[\"Promoted\",\"Nice result that still needs improvement. Keep making efforts for better grades. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2173045', '[\"Mr. Enechukwu Emmanuel \",\"Poor result. He is easily distracted during studies. He can improve on this if he could convert his play time to his study time. \"]', '[\"Promoted\",\"He can do much better if he works harder. Please advise him never to relent. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2121859', '[\"Mr. Enechukwu Emmanuel \",\"Nice result. Kyrian needs to put more effort in his studies. \"]', '[\"Promoted\",\"A very good result that still needs improvement.  Keep making efforts for better grades. He was voted the best behaved by his classmates, and should keep this up. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2172610', '[\"Mr. Enechukwu Emmanuel \",\"Very poor result. Vitus lacks attention during studies and classes. He should be encouraged to put more effort in his studies. \"]', '[\"Promoted\",\"Very poor result. Improve! Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2188336', '[\"Mr. Enechukwu Emmanuel \",\"Very poor result. Raymond plays and sleeps too much during studies. If he could pay serious attention to his studies, then he will perform better. \"]', '[\"Promoted\",\"Very poor result. Raymond is easily distracted and can do better if he remains focused. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2188629', '[\"Mr. Enechukwu Emmanuel \",\"Poor result. Francis lacks concentration during studies. He should be encouraged to put more effort in his studies. \"]', '[\"Promoted\",\"Poor result. Please sit up and strive for a better result. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2146558', '[\"Mr. Enechukwu Emmanuel \",\"Poor result. Louis is easily distracted during studies. He can improve on this if he decides to pay serious attention to his studies \"]', '[\"Promoted\",\"Louis has recorded a very poor performance, and must be cautioned to sit up. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2180559', '[\"Mr. Enechukwu Emmanuel \",\"Fair result. Emmanuel should put more effort in his studies. \"]', '[\"Promoted\",\"This performance is only a narrow escape, and it is not encouraging. Pay attention to Latin and Mathematics, amongst others. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2129669', '[\"Mr. Enechukwu Emmanuel \",\"Wonderful result. He pays serious attention during studies and I know he can do more than this. Keep improving \"]', '[\"Promoted\",\"A very good result that still needs improvement. Keep making efforts for better grades. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2188593', '[\"Mr. Enechukwu Emmanuel \",\"Raphael should learn to convert his play time to his study time in order to improve on this. \"]', '[\"Promoted\",\"Abysmally poor performance. Please caution him to be more focused in his academic life. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2138425', '[\"Mr. Enechukwu Emmanuel \",\"Fair result. You can improve on this. \"]', '[\"Promoted\",\"This is a very poor result. He should pay more attention to his studies and avoid distractions during classes. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2158686', '[\"Mr. Enechukwu Emmanuel \",\"Poor result. John lacks concentration  during studies. Am sure he can improve on this if he decides to study his books sequentially. \"]', '[\"Promoted\",\"Very poor performance. He should avoid too much complaints, and face his formation! \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2144979', '[\"Mr. Enechukwu Emmanuel \",\"Fair result. You can still improve on this result. \"]', '[\"Promoted\",\"Poor result! Please advise him to improve especially on the failed subjects\",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2109488', '[\"Mr. Enechukwu Emmanuel \",\"Poor result. Francis is easily distracted during studies. He should be encouraged to put more effort i n his studies. \"]', '[\"Promoted\",\"Very poor performance. Please sit up and say no to your defeat. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2185190', '[\"Mr. Enechukwu Emmanuel \",\"Nice result. Keep improving. \"]', '[\"Promoted\",\"A fair result that still needs improvement. Keep making efforts for better grades. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2186225', '[\"Mr. Enechukwu Emmanuel \",\"Fair result. Kingsley lacks concentration during studies. He should put more effort in his studies. \"]', '[\"Promoted\",\"Fairly good result. Pay serious attention to the failed subjects and the core ones. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2111338', '[\"Mr. Enechukwu Emmanuel \",\"Fair result. Pedro needs to pay serious attention to his studies. \"]', '[\"Promoted\",\"Pedro, this result is only a narrow escape. The scores are so low! Get yourself ready for serious studies in future. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2118869', '[\"Mr. Enechukwu Emmanuel \",\"Nice result. Emmanuel can do more than this if he decides to put more effort in his studies. \"]', '[\"Promoted\",\"A fairly good result that still needs improvement. Keep making efforts for better grades. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2164998', '[\"Mr. Enechukwu Emmanuel \",\"Excellent result. Keep it up. \"]', '[\"Promoted\",\"Excellent performance! Kingsley is a jovial, docile, dedicated and duty-conscious seminarian. He should be encouraged to keep this up. Conduct quite satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2178453', '[\"Mr. Enechukwu Emmanuel \",\"Wonderful result. Keep improving. \"]', '[\"Promoted\",\"A very good result! Collins is always neat, and pays attention in the class. He should keep this up. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2116430', '[\"Mr. Enechukwu Emmanuel \",\"Excellent result. Innocent can do more than this. \"]', '[\"Promoted\",\"An impressive performance! Innocent is really making giant strides in his academic performance. Encourage him to do more. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2154360', '[\"Mr. Enechukwu Emmanuel \",\"Nice result. Anthony needs to put more effort in his studies. \"]', '[\"Promoted\",\"A fairly good result that still needs improvement. Keep making efforts for better grades. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2115692', '[\"Mr. Kingsley Okafor\",\"Nice result Alex. Keep it up. You can do better than this.\"]', '[\"Promoted\",\"Very good result. There is still room for improvement. Conduct satisfactory\\r\\n\",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2163521', '[\"Mr. Kingsley Okafor\",\"Stanley should try to concentrate more on his studies,especially in science courses.Fair result\"]', '[\"Promoted\",\"There is need for improvement. Fairly good result. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2146808', '[\"Mr. Kingsley Okafor\",\"Victor is a serious minded seminarian,he is always serious with his studies. Nice result.\"]', '[\"Promoted\",\"Pay attention to the subjects you scored low grades. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2141876', '[\"Mr. Kingsley Okafor\",\"Paschal is a serious minded seminarian.He is always serious with his studies.Nice result.\"]', '[\"Promoted\",\"A good result. Keep improving. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2146563', '[\"Mr. Kingsley Okafor\",\"Chrysogonus, you need to work harder in your academics.He is easily distracted.Fair result.\"]', '[\"Promoted\",\"Very poor result. Please wake up before it is too late. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2144789', '[\"Mr. Kingsley Okafor\",\"Ignatius,this is not your best,you can do better than this.He is hardworking.\"]', '[\"Promoted\",\"You can do better than this. Sit up and study harder. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2114178', '[\"Mr. Okafor Kingsley\",\"Nice result Christopher. Keep it up.\"]', '[\"Promoted\",\"A fairly good result. Keep making efforts for better grades. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2128883', '[\"Mr. Kingsley Okafor\",\"Nice result Francis.He is a serious minded seminarian.Keep it up.\"]', '[\"Promoted\",\"A fairly good result. Keep making efforts for better grades. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2135105', '[\"Mr. Kingsley Okafor\",\"Valentine is a serious minded seminarian.You can still do more than this.Nice result.\"]', '[\"Promoted\",\"A fairly good result. Keep making efforts for better grades. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2105599', '[\"Mr. Kingsley Okafor\",\"Johnbosco, you went back this term.Sit up next term.Nice result.\"]', '[\"Promoted\",\"A fairly good result, but you used to do much better. Keep making efforts for better grades. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2195498', '[\"Mr. Kingsley Okafor\",\"Superb.Nice result.Keep it up Victor.\"]', '[\"Promoted\",\"Very good result! Keep making efforts for better grades. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2181542', '[\"Mr. Kingsley Okafor\",\"He is studious.Nice result Emmanuel,keep it up.\"]', '[\"Promoted\",\"A fairly good result. Keep making efforts for better grades. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2164967', '[\"Mr. Kingsley Okafor\",\"Francis what really happened?.You went back this term,work harder next term.Fair result.\"]', '[\"Promoted\",\"A fairly good result, but much below your standard. Keep making efforts for better grades. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2157915', '[\"Mr. Kingsley Okafor\",\"Sixtus, this is not your best.Work harder next term.Fair result.\"]', '[\"Promoted\",\"A fairly good result, but there is room for improvement. Keep making efforts for better grades. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2134831', '[\"Mr. Kingsley Okafor\",\"Gideon is very hardworking.Nice result.Keep it up\"]', '[\"Promoted\",\"A good result. Keep making efforts for better grades. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2168844', '[\"Mr. Kingsley Okafor\",\"Eugene,you have to sit up.This is not your best.Fair result.\"]', '[\"Promoted\",\"A fairly good result that can be improved upon. Keep making efforts for better grades. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2152653', '[\"Mr. Kingsley Okafor\",\"Johnbosco is a noisy seminarian.Work harder next term.Fair result.\"]', '[\"Promoted\",\"Fair result. He can do better if he regulates his classroom conduct. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2146921', '[\"Mr. Kingsley Okafor\",\"Bonaventure is a serious seminarian.You have to sit up next term in your studies.\"]', '[\"Promoted\",\"This is fair, but not wonderful. Strive better next time. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2131925', '[\"Mr. Kingsley Okafor\",\"Johnpaul should pay attention in his studies,especially in science courses.Fair result\"]', '[\"Promoted\",\"A fairly good result that can be improved on. Keep making efforts for better grades. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2185507', '[\"Mr. Kingsley Okafor\",\"Augustine is easily distracted in class,but he is hardworking and dedicated.Work harder next term.\"]', '[\"Promoted\",\"He really can do better if he regulates his classroom conduct. Fair result. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2162614', '[\"Mr. Kingsley Okafor\",\"Nice result Timothy.Keep it up.\"]', '[\"Promoted\",\"A fairly result. Keep making efforts for better grades, and avoid bullying  younger ones. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2156186', '[\"Mr. Kingsley Okafor\",\"Reginald sleeps alot in the class.He needs to work harder next term.Poor result.\"]', '[\"Promoted\",\"Poor result. Please caution him to be more responsible in the classroom. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2144916', '[\"Mr. Kingsley Okafor\",\"Nice result Charles.Keep it up.\"]', '[\"Promoted\",\"Very good result. Keep making efforts for even better grades. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2165865', '[\"Mr. Kingsley Okafor\",\"Victor sleeps alot in the classroom.He needs to work harder academically next term.Fair result.\"]', '[\"Promoted\",\"Fair result. But he can do much better if he pays more attention in class. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2183674', '[\"Mr. Kingsley Okafor\",\"Superb.Nice result Emmanuel.Keep it up.\"]', '[\"Promoted\",\"Wonderful result! Keep making efforts for better grades. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2183835', '[\"Mr. Kingsley Okafor\",\"Benedict is easily distracted during studies.He should sit up next term.Fair result.\"]', '[\"Promoted\",\"A fairly good result. Keep making efforts for better grades. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2152131', '[\"Mr. Kingsley Okafor\",\"Nice result Hilary.Keep it up.\"]', '[\"Promoted\",\"A fairly good result. Keep making efforts for better grades. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2141158', '[\"Mr. Kingsley Okafor\",\"Marcellinus, you really went back this term.This is not your best,you can do better than this.Nice result\"]', '[\"Promoted\",\"A fairly good result. Replicate your score in Book Keeping in other subjects. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2144579', '[\"Mr. Kingsley Okafor\",\"Nice result Frank.Keep it up.You can still take the first position.\"]', '[\"Promoted\",\"Wonderful result! You can do even better. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2163304', '[\"Mr. Kingsley Okafor\",\"Nice result Francis.You can do better than this, if only you will stop distracting yourself.\"]', '[\"Promoted\",\"Nice result. Pay more attention to Geography and Government. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2127476', '[\"Mr. Kingsley Okafor\",\"Nice result John. Keep it up.He is a serious minded student.\"]', '[\"Promoted\",\"A fairly good result. Keep making efforts for better grades. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2118873', '[\"Mr. Kingsley Okafor\",\"Nice result Alphonsus.Keep it up.He is a serious minded student.\"]', '[\"Promoted\",\"A nice result. Keep making efforts for better grades. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2134142', '[\"Mr. Kingsley Okafor\",\"Michael is a noisy Seminarian. He should sit up next term.Fair result.\"]', '[\"Promoted\",\"A fairly good result. Keep making efforts for better grades, especially in Physics and Mathematics. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2185638', '[\"Mr. Kingsley Okafor\",\"Valentine is trying his best,but I believe he can do better than this if he should put more effort. Fair result.\"]', '[\"Promoted\",\"A fairly good result. Keep making efforts for better grades. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2167843', '[\"Mr. Kingsley Okafor\",\"Nice result Hilary. Keep it up.\"]', '[\"Promoted\",\"A very good result. Keep making efforts for better grades. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2135719', '[\"Mr. Enechukwu Emmanuel \",\"Nice result. Keep improving \"]', '[\"Promoted\",\"A very good result that still needs improvement. Keep making efforts for better grades. Conduct satisfactory. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2147943', '[\"Mr. Kingsley Okafor\",\"Collins is easily distracted in classroom.He needs to concentrate more in his studies.Fair result.\"]', '[\"Promoted\",\"Poor result. He needs to sit up or risk more failures in future. \",\"Rev. Fr. Paul-Mary Chukwukebe\"]'),
('SJBSI2192046', '[\"Mr. Kingsley Okafor\",\"David, you have to brace up for actions next term. You have only one slot.Concentrate more in your studies and you will surely make it.Poor result.\"]', '[\"Promoted\",\"Abysmally poor performance. Please wake up! \",\"Rev. Fr. Paul-Mary Chukwukebe\"]');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `stud_de`
--
ALTER TABLE `stud_de`
  ADD PRIMARY KEY (`stud_id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `stud_de`
--
ALTER TABLE `stud_de`
  MODIFY `stud_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=657;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
