<?php 
 $i = 1;
 $stud_avr= array(0,0,0);
 echo json_encode($stud_avr);
 die();
 arsort($stud_avr);
 foreach ($stud_avr as $k => $v) {
     if($v == $old){
        $h = $i;
        $hh = $h - 1;
       echo '<br>'.$hh .' as the value is '.$v;
     }else{
        echo '<br>'.$i .' as the value is '.$v;  
     }
     $old = $v; 
     $i++;
 }
 

 
 INSERT INTO `admit` (`catig`, `class`, `name`, `exam_n`, `stats`) VALUES
(1,1,'EGBO SAMUEL KELECHUKWU',	'IS/128 ','PASSED'),
(1,1,'EZEGO   GERALD  ARINZECHUKWU' ,'IS/129	','FAILED'),
(1,1,'DUNU  CHUKWUDALU EMMANUEL	' ,'IS/130	','PASSED'),
(1,1,'EBOLUE   MARTINS CHUKWUEBUKA	' ,'LE/IS/001	','PASSED'),
(1,1,'EZENWOKE  CHARLES-MELVIN CHKAIMA' ,'	LE/IS/002	','FAILED'),
(1,1,'NWAFOR   EMMANUEL   IFECHUKWU	' ,'LE/IS/003	','PASSED'),
(1,1,'OKWUROKA   CHIZOBA    FIDELIS	' ,'LE/IS/004	','FAILED'),
(1,1,'OFODUM  CHIBUIKE  VICTOR' ,'	LE/IS/005	','PASSED'),
(1,1,'ENWERE    EMMANUEL  AKACHUKWU	' ,'LE/IS/006	','PASSED'),
(1,1,'UKOH     ANTHONY   EKENEDIRICHUKWU' ,'	LE/IS/007	','PASSED'),
(1,1,'OGAMBA     CHIMAMANDA  INNOCENT	' ,'LE/IS/008	','PASSED'),
(1,1,'OGAMBA    ANTHONY    CHINEMEMMA	' ,'LE/IS/009	','FAILED'),
(1,1,'MADUKAIFE  CHIBUIKE  JOHN MARTINS PIO	' ,'LE/IS/010	','FAILED'),
(1,1,'OJILE    ANTHONY      CHIDERA	' ,'LE/IS/011 	','PASSED'),
(1,1,'EMENGINI     ONYEMAECHI   PASCHAL' ,'	LE/IS/012	','PASSED'),
(1,1,'EZE  GERALD    CHIKAMSO 	' ,'LE/IS/013	','PASSED'),
(1,1,'NZEKWE   EBUBECHUKWU   VALERIAN 	' ,'LE/IS/014	','PASSED'),
(1,1,'EWUZIE   CHUKWUEBUKA    EMMANUEL	' ,'LE/IS/015	','PASSED'),
(1,1,'EWUZIE   CHUKWUDALU      NOEL	' ,'LE/IS/016	','PASSED'),
(1,1,'ANYAORA  CHIMERAOGO  FRANKLYN	' ,'LE/IS/017	','PASSED'),
(1,1,'OKONKWO  EMMANUEL    IGWEBUIKE	' ,'LE/IS/018	','FAILED'),
(1,1,'UGWUEGU  KINGSLEY     EBUKA	' ,'LE/IS/019A	','FAILED'),
(1,1,'CHUKWUMA   JOHNBOSCO      CHIDERA	' ,'LE/IS/019B	','PASSED'),
(1,1,'PATRICK         CHIDERA      PASCHAL	' ,'LE/IS/020A	','PASSED'),
(1,1,'NONYELU  JOHN     CHIKA	' ,'LE/IS/020B	','PASSED'),
(1,1,'UDORJI    STANLEY     CHIBUIKE	' ,'LE/IS/022	','FAILED'),
(1,1,'OKPALA  IFECHUKWU    URIEL	' ,'LE/IS/024	','PASSED'),
(1,1,'OKPALA   STANLEY  CHIAGOZIE	' ,'LE/IS/025	','PASSED'),
(1,1,'NNAMA    KINGSLEY    CHIDIEBRE	' ,'LE/IS/026	','PASSED'),
(1,1,'NNAEMEGO  CHIDI    DOMINIC	' ,'LE/IS/027	','PASSED'),
(1,1,'EJIOFOR     CHILOTAM      TOBY	' ,'LE/IS/028	','PASSED'),
(1,1,'IFEDIEGWU    CHIDUBEM     EMMANUEL	' ,'LE/IS/029	','FAILED'),
(1,1,'NWACHUKWU   AUGUSTINE   SOMKENE	' ,'LE/IS/030	','PASSED'),
(1,1,'OKAFOR   GERALD MARY ONYEDIKA	' ,'LE/IS/031	','FAILED'),
(1,1,'ANIKE  PASCHAL    AMARACHI	' ,'LE/IS/032	','PASSED'),
(1,1,'CHEKWA   KENECHUKWU     EVANS	' ,'LE/IS/033	','PASSED'),
(1,1,'ATTAJADUMI  BONAVENTURE	' ,'LE/IS/034	','PASSED'),
(1,1,'ATTAJADUMI   VALERIAN	' ,'LE/IS/035	','PASSED'),
(1,1,'MBAH-CHUKWUEDOZIE   VALENTINE   C.	' ,'LE/IS/036	','FAILED'),
(1,1,'ANAZODO  JOHNBOSCO  CHIAGOZIE	' ,'LE/IS/037	','PASSED'),
(1,1,'EZE  GERALD    IKEDI	' ,'LE/IS/038	','FAILED');

 
 
 
 
 
 
?>